version: 2.1
jobs:
    run-playwright-tests:
        docker:
            - image: mcr.microsoft.com/playwright:v1.43.1-jammy
        steps:
            - checkout
            - run:
                  name: Install dependencies
                  command: npm install
            - run:
                  name: Install Playwright browsers
                  command: npx playwright install --with-deps
            - run:
                  name: Run Playwright tests
                  command: npm run all-tests
            - store_test_results:
                  path: test-results/
            - store_artifacts:
                  path: playwright-report/
